// response-codes.js
const { StatusCodes } = require('http-status-codes');

const RESPONSE_CODE = {
  OK: StatusCodes.OK,
  CREATED: StatusCodes.CREATED,
  ACCEPTED: StatusCodes.ACCEPTED,
  NO_CONTENT: StatusCodes.NO_CONTENT,
  MOVED_PERMANENTLY: StatusCodes.MOVED_PERMANENTLY,
  BAD_REQUEST: StatusCodes.BAD_REQUEST,
  UNAUTHORIZED: StatusCodes.UNAUTHORIZED,
  FORBIDDEN: StatusCodes.FORBIDDEN,
  NOT_FOUND: StatusCodes.NOT_FOUND,
  METHOD_NOT_ALLOWED: StatusCodes.METHOD_NOT_ALLOWED,
  INTERNAL_SERVER_ERROR: StatusCodes.INTERNAL_SERVER_ERROR,
  SERVICE_UNAVAILABLE: StatusCodes.SERVICE_UNAVAILABLE,
  GATEWAY_TIMEOUT: StatusCodes.GATEWAY_TIMEOUT,
  CONFLICT: StatusCodes.CONFLICT,
  UNPROCESSABLE_ENTITY: StatusCodes.UNPROCESSABLE_ENTITY,
  GONE: StatusCodes.GONE,
  TOO_MANY_REQUESTS: StatusCodes.TOO_MANY_REQUESTS,
};

module.exports = RESPONSE_CODE;
