// Define available routes
import {
  Home,
  Briefcase,
  ClipboardList,
  Search,
  History,
  Package,
  ShoppingCart,
  Repeat,
  FileText,
  Car,
  Users,
  CreditCard,
  DollarSign,
  FileMinus,
  Settings,
  Calendar,
  Megaphone,
  Tag,
  Gift,
  Newspaper,
  ListChecks,
  HelpCircle,
  Lightbulb,
  Share2,
  Images,
  Bell,
} from 'lucide-react';

// export const quickSearchRoutes = [
//   { name: "Dashboard", path: "/", icon: Home },
//   { name: "Jobs", path: "/jobs", icon: Briefcase },
//   { name: "Completed Jobs", path: "/jobs/completed", icon: ClipboardList },
//   { name: "Search Jobs", path: "/jobs/search", icon: Search },
//   { name: "Empty Jobs", path: "/jobs/empty", icon: FileText },
//   { name: "Cab History", path: "/cabhistory", icon: History },
//   { name: "Spare Parts", path: "/spareparts", icon: Package },
//   { name: "Used Spare Parts", path: "/inventory/used", icon: Package },
//   { name: "New Spare Parts", path: "/inventory/new", icon: Package },
//   { name: "Return Spare Parts", path: "/inventory/return", icon: Repeat },
//   {
//     name: "Purchase Spare Parts",
//     path: "/inventory/purchase",
//     icon: ShoppingCart,
//   },
//   { name: "Purchase Return", path: "/inventory/purchase-return", icon: Repeat },
//   { name: "Memo", path: "/memo", icon: FileText },
//   { name: "Cars", path: "/cars", icon: Car },
//   { name: "Customers", path: "/customers", icon: Users },
//   { name: "Accounts", path: "/accounts", icon: CreditCard },
//   { name: "Account Statements", path: "/accounts/statements", icon: FileText },
//   { name: "General Ledger", path: "/accounts/ledger", icon: FileText },
//   {
//     name: "Supplier Payment",
//     path: "/accounts/supplier-payment",
//     icon: DollarSign,
//   },
//   { name: "Invoices", path: "/accounts/invoices", icon: FileMinus },
//   { name: "Expenses", path: "/accounts/expenses", icon: DollarSign },
//   { name: "Employees", path: "/hrms/employee", icon: Users },
//   { name: "Payroll", path: "/hrms/payroll", icon: DollarSign },
//   { name: "Announcements", path: "/hrms/announcements", icon: Megaphone },
//   { name: "Holidays", path: "/hrms/holidays", icon: Calendar },
//   { name: "Reports", path: "/reports", icon: FileText },
//   { name: "Settings", path: "/settings", icon: Settings },
// ];

export const quickSearchRoutes = [
  { name: 'Dashboard', path: '/', icon: Home },
  { name: 'Users', path: '/users', icon: Users },
  { name: 'Coupons', path: '/coupons', icon: Tag },
  { name: 'Referrals', path: '/referrals', icon: Gift },
  { name: 'News', path: '/news', icon: Newspaper },
  { name: 'News Category', path: '/news/category', icon: ListChecks },
  { name: 'FAQ', path: '/faq', icon: HelpCircle },
  { name: 'Trade Tips', path: '/tradetips', icon: Lightbulb },
  { name: 'Social Links', path: '/social-links', icon: Share2 },
  { name: 'media-assets', icon: Images, path: '/media-assets/home' },
  { name: 'notifications', icon: Bell, path: '/notifications/home' },
  { name: 'Plans', path: '/plans', icon: CreditCard },
  { name: 'Settings', path: '/settings', icon: Settings },
];
